<a href="https://colab.research.google.com/github/abhishekchopra0907/Malaria-detection-using-cell-images/blob/master/neural_scratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import math
import random as rd
import matplotlib.pyplot as plt
import math
from sklearn.preprocessing import MinMaxScaler



In [0]:
def sigmoid(num):
  a= 1.0/(1.0+np.exp(-1.0*num))
  return a
    
def relu(x):
  return np.maximum(x,0)

def tanh(x):
  return np.tanh(x)

In [0]:


def der_relu(z):
    return np.where(z <= 0, 0, 1)
def tanh_deriv(x):
    return 1.0 - np.tanh(x)**2

In [0]:


def linear_func(input_node,weight,bias):
  ##node_output=np.dot(input_node,weight)+bias
  node_output=np.dot(input_node,weight)
  
  return node_output/20

In [0]:
def bias_wieght_initial(input_dimention,output_node1,output_node2):
  weight1=np.random.rand(input_dimention,output_node1)
  weight2=np.random.rand(output_node1,output_node2)
  bias1=np.zeros(output_node1)
  bias2=np.zeros(output_node2)
  return weight1,weight2,bias1,bias2

In [0]:
def linear_block(input_to_node,weight,bias):
    node_output =np.dot(input_to_node,weight) +bias
    return node_output

In [0]:
def der_sigmoid(x):
  return x*(1-x)
##differential of sigmoid is sigmoid*(1-sigmoid)

In [0]:
def forward_pass(data,weight1,bias1,weight2,bias2):
  linear1=linear_func(data,weight1,bias1)
  ##we are having to do this element wise because sigmoid func only takes in an integar value and not a array one 
  non_linear1=sigmoid(linear1)
  linear2=linear_func(non_linear1,weight2,bias2)
  print(linear2[0:3])
  return linear2,non_linear1

In [0]:

def backward_pass(data,output,hidden_output,weight1,weight2,bias1,bias2,error):
  partial_derivative_beta=np.dot(hidden_output.T,error)
  partial_derivative_alpha_withoutdata=np.multiply(np.dot(error,weight2.T),der_sigmoid(hidden_output))
  partial_derivative_alpha=np.dot(data.T,partial_derivative_alpha_withoutdata)
  delta_bias2=np.sum(error,axis=0)
  delta_bias1=np.sum(partial_derivative_alpha_withoutdata,axis=0)
  learning_rate=0.1
  updated_weight1=weight1-learning_rate*partial_derivative_alpha
  updated_weight2=weight2-learning_rate*partial_derivative_beta
  updated_bias1=bias1-learning_rate*delta_bias1
  updated_bias2=bias2-learning_rate*delta_bias2
  return updated_weight1,updated_bias1,updated_weight2,updated_bias2

In [0]:

def train(data,labels,test_data,test_labels,weight1,weight2,bias1,bias2,epoch):
  Total_train_loss=[]
  Total_test_loss=[]
  Number_of_datapoints =data.shape[0]
  for i in range(epoch):
    output,hidden=forward_pass(data,weight1,bias1,weight2,bias2)
    error=output-labels
    #error = keras.utils.to_categorical(error, 10)
    Squared_error_loss = np.sum(0.5*(output-labels)**2)
    Mean_squared_error_loss = Squared_error_loss / Number_of_datapoints
    weight1,bias1,weight2,bias2=backward_pass(data,output,hidden,weight1,weight2,bias1,bias2,error)
    print("\n")
    print("weight 1")
    print( weight1)
    print("\n")
    print("weight 2")
    
    print(weight2)
    print("\n")
    print("bias 1")
    
    print(bias1)
    print("\n")
    print("bias 2")
    
    print(bias2)
    output_val,hidden_val=forward_pass(test_data,weight1,bias1,weight2,bias2)
    yes=np.argmax(output_val,axis=1)
    Test_loss = np.sum(0.5*(output_val-test_labels)**2)
    Test_loss/=Number_of_datapoints
    Total_train_loss=np.append(Total_train_loss,Mean_squared_error_loss)
    Total_test_loss=np.append(Total_test_loss,Test_loss)
  return Total_train_loss,Total_test_loss,weight1,weight2,bias1,bias2,yes
  

In [0]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import RMSprop
import matplotlib.pyplot as plt


num_classes,num_nueron = 10,50
epoch = 1

# the data, shuffled and split between train and test sets
(x_train, y_train), (x_test, y_test) = mnist.load_data()
y_train = keras.utils.to_categorical(y_train, 10)
y_test =error = keras.utils.to_categorical(y_test, 10)
x_train = x_train.reshape(60000, 784)
x_test = x_test.reshape(10000, 784)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
x_train /= 255
x_test /= 255
print(x_train.shape[0], 'train samples')
print(x_test.shape[0], 'test samples')
weight1,weight2,bias1,bias2=bias_wieght_initial(x_train.shape[1],num_nueron,num_classes)

print(train(x_train,y_train,x_test,y_test,weight1,weight2,bias1,bias2,epoch))

60000 train samples
10000 test samples
[[1.14923019 1.15965894 1.23099279 1.19814628 1.04015052 1.04446691
  1.20602439 1.28529758 1.22705984 1.1059242 ]
 [1.1721949  1.18179088 1.25560358 1.21999483 1.06078895 1.06568641
  1.23085249 1.31068235 1.25216703 1.1272716 ]
 [1.07102427 1.08207726 1.14713926 1.11811031 0.96809351 0.97327935
  1.12663113 1.1987812  1.14597236 1.03205728]]


weight 1
[[0.17858868 0.57967028 0.94841009 ... 0.97235007 0.3483637  0.68471242]
 [0.36308714 0.26010235 0.41703446 ... 0.33951986 0.21342384 0.07280652]
 [0.78803658 0.90165669 0.54972391 ... 0.95778581 0.39929418 0.27529445]
 ...
 [0.55054188 0.30926199 0.54417717 ... 0.87582073 0.02452406 0.8984024 ]
 [0.54973112 0.25556648 0.04851169 ... 0.02967828 0.22707488 0.765393  ]
 [0.80020788 0.45704305 0.22444909 ... 0.1259896  0.06090194 0.32480031]]


weight 2
[[-5584.3581132  -5650.70959105 -6026.94467124 -5845.14739277
  -5030.51496961 -5095.48562356 -5907.13822071 -6313.52337826
  -6021.77214746 -5377.71

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  


In [0]:
print(np.random.rand(2,2))

[[0.88112315 0.54434641]
 [0.90043908 0.70789184]]


In [0]:
sigmoid(51.18141993167)


0.03333333333333333

In [0]:
print(sigmoid(linear_func(x_train,weight1,bias1)))

[[0.03121341 0.03062042 0.03139866 ... 0.03144027 0.03085867 0.03149688]
 [0.03192406 0.03134515 0.03182241 ... 0.03186308 0.03181937 0.03220767]
 [0.0293468  0.0289858  0.02934987 ... 0.02926065 0.02934564 0.02901426]
 ...
 [0.02981026 0.02969194 0.03019979 ... 0.03025777 0.03007434 0.02992911]
 [0.02923455 0.02929068 0.02923768 ... 0.02922419 0.02951272 0.02954923]
 [0.03006242 0.02953244 0.02963212 ... 0.02921494 0.02967059 0.02976478]]


In [0]:
x_train[0]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     